---
# ***************************************
#
# * Linux Configuration Playbooks
#
# ***************************************

# On RedHat based OS, run first prerpm.yaml playbook

- hosts: all
  user: fsalaman
  become: yes
  vars:
    with_proxy: false
    with_containers: true
    with_kubernetes: true
    theuser: "root"
  environment:
#    HTTP_PROXY: http://proxy.example.com:3128
#    https_proxy: http://proxy.example.com:3128
#    http_proxy: http://proxy.example.com:3128
#    HTTPS_PROXY: http://proxy.example.com:3128
  roles:
    - roles/preconfig
    - roles/containers
    - role: freehck.disable_swap
    - roles/kubernetes

- hosts: masters
  user: fsalaman
  become: yes
  vars:
    with_proxy: false
    with_containers: true
    with_kubernetes: true
    theuser: "root"
  environment:
#    HTTP_PROXY: http://proxy.example.com:3128
#    https_proxy: http://proxy.example.com:3128
#    http_proxy: http://proxy.example.com:3128
#    HTTPS_PROXY: http://proxy.example.com:3128
  roles:
    - roles/masters

- hosts: workers
  user: fsalaman
  become: yes
  vars:
    with_proxy: false
    with_containers: true
    with_kubernetes: true
    theuser: "root"
  environment:
#    HTTP_PROXY: http://proxy.example.com:3128
#    https_proxy: http://proxy.example.com:3128
#    http_proxy: http://proxy.example.com:3128
#    HTTPS_PROXY: http://proxy.example.com:3128
  roles:
    - roles/workers

