---
# ***************************************
#
# * Linux Configuration Playbooks
#
# ***************************************

# Prepare RedHat based Linux hosts
- hosts: all
  user: centos
  become: yes
  vars:
    with_proxy: false
    theuser: "root"
  environment:
#    HTTP_PROXY: http://proxy.example.com:3128
#    https_proxy: http://proxy.example.com:3128
#    http_proxy: http://proxy.example.com:3128
#    HTTPS_PROXY: http://proxy.example.com:3128
  roles:
    - roles/prerpm
