---
# include file for kubernetes - Debian based OS

- name: Add K8s signing apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add K8s APT repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install K8s
  apt:
    name: kubelet,kubeadm,kubectl
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Holds K8s packages
  dpkg_selections:
    name: "{{ item.package }}"
    selection: hold
  with_items:
    - { package: "kubelet" }
    - { package: "kubeadm" }
    - { package: "kubectl" }
  when: ansible_facts['os_family'] == "Debian"
