---
# tasks file for kubernetes

- include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: rpmbased.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: K8s - restart kubelet
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: kubelet

