---
# tasks file for containers

- name: Install Docker Python SDK
  pip:
    name: docker
    state: present

- include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: rpmbased.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Load modules right now
  systemd:
    name: systemd-modules-load
    state: restarted

- name: Enable required kernel parameters
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    reload: yes 

- name: Enable required kernel parameters
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    reload: yes 
