---
# Include for RedHat based

- name: Install dnf-plugins-core
  yum:
    name: dnf-plugins-core
    state: present
  when: ansible_facts['os_family'] == "RedHat" 

- name: Add Docker DNF Repo (Fedora)
  yum_repository:
    name: Docker.io
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/fedora/34/x86_64/stable/
    gpgcheck: no
  when: ansible_distribution == "Fedora"

- name: Add Docker DNF Repo (CentOS 8)
  yum_repository:
    name: Docker.io
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
    gpgcheck: no
  when: ansible_distribution == "CentOS 8"

- name: Install Docker (RPM)
  yum:
    name: docker-ce,containerd.io
    state: present
  when: ansible_facts['os_family'] == "RedHat" 

- name: Enable required kernel modules - Red Hat/CentOS
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'modules', dest: '/etc/modules-load.d/k8s.conf' }
  when: ansible_facts['os_family'] == "RedHat"

- name: Open required ports
  firewalld:
#    zone: public
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 80/tcp
    - 443/tcp
    - 6443/tcp
    - 8443/tcp
    - 2379-2380/tcp
    - 10250-10252/tcp
    - 30000-32767/tcp
  when: ansible_facts['os_family'] == "RedHat"

- name: Reload firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable Docker - systemd
  systemd:
    name: docker
    state: restarted
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"


